const Data = [
    {
      "name": "Lesa Black",
      "rating": 2.7,
      "speciality": "Surgery",
      "gender": "female",
      "email": "lesablack@uniworld.com",
      "phone": "+1 (848) 467-3313",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Underhill Avenue"
    },
    {
      "name": "Riggs Marsh",
      "rating": 2.9,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "riggsmarsh@uniworld.com",
      "phone": "+1 (802) 532-3660",
      "city": "Concord",
      "state": "CA",
      "street": "Irwin Street"
    },
    {
      "name": "Mclaughlin Juarez",
      "rating": 2.5,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "mclaughlinjuarez@uniworld.com",
      "phone": "+1 (895) 582-2345",
      "city": "San Francisco",
      "state": "CA",
      "street": "Irvington Place"
    },
    {
      "name": "Terra Mcmillan",
      "rating": 1.9,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "terramcmillan@uniworld.com",
      "phone": "+1 (857) 592-3378",
      "city": "Concord",
      "state": "CA",
      "street": "Kenmore Court"
    },
    {
      "name": "Dona Hodge",
      "rating": 3.8,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "donahodge@uniworld.com",
      "phone": "+1 (989) 445-3559",
      "city": "Oakland",
      "state": "CA",
      "street": "Gerald Court"
    },
    {
      "name": "Preston Todd",
      "rating": 4.8,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "prestontodd@uniworld.com",
      "phone": "+1 (987) 518-3894",
      "city": "Concord",
      "state": "CA",
      "street": "Grace Court"
    },
    {
      "name": "Holland Tillman",
      "rating": 2.2,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "hollandtillman@uniworld.com",
      "phone": "+1 (845) 400-3121",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Holly Street"
    },
    {
      "name": "Langley Waters",
      "rating": 2.8,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "langleywaters@uniworld.com",
      "phone": "+1 (905) 516-2662",
      "city": "San Jose",
      "state": "CA",
      "street": "Bethel Loop"
    },
    {
      "name": "Maura Larson",
      "rating": 3.2,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "mauralarson@uniworld.com",
      "phone": "+1 (815) 549-3278",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Chester Street"
    },
    {
      "name": "Cruz Harper",
      "rating": 3.4,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "cruzharper@uniworld.com",
      "phone": "+1 (934) 561-2085",
      "city": "San Jose",
      "state": "CA",
      "street": "Irving Street"
    },
    {
      "name": "Vera Gilmore",
      "rating": 3.3,
      "speciality": "Surgery",
      "gender": "female",
      "email": "veragilmore@uniworld.com",
      "phone": "+1 (945) 527-2811",
      "city": "San Jose",
      "state": "CA",
      "street": "Vanderbilt Avenue"
    },
    {
      "name": "Skinner Bridges",
      "rating": 4.2,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "skinnerbridges@uniworld.com",
      "phone": "+1 (883) 536-3722",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Evergreen Avenue"
    },
    {
      "name": "Berger Baxter",
      "rating": 2.4,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "bergerbaxter@uniworld.com",
      "phone": "+1 (848) 465-3489",
      "city": "Concord",
      "state": "CA",
      "street": "Amber Street"
    },
    {
      "name": "Juliette Hines",
      "rating": 4.3,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "juliettehines@uniworld.com",
      "phone": "+1 (973) 513-3060",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Amboy Street"
    },
    {
      "name": "Mosley Gould",
      "rating": 2.9,
      "speciality": "Surgery",
      "gender": "male",
      "email": "mosleygould@uniworld.com",
      "phone": "+1 (959) 596-3685",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Gallatin Place"
    },
    {
      "name": "Carly Mcpherson",
      "rating": 2.4,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "carlymcpherson@uniworld.com",
      "phone": "+1 (978) 443-2107",
      "city": "San Francisco",
      "state": "CA",
      "street": "Laurel Avenue"
    },
    {
      "name": "Mann Hays",
      "rating": 5,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "mannhays@uniworld.com",
      "phone": "+1 (812) 515-3448",
      "city": "Concord",
      "state": "CA",
      "street": "Etna Street"
    },
    {
      "name": "Alford Durham",
      "rating": 5,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "alforddurham@uniworld.com",
      "phone": "+1 (876) 459-2595",
      "city": "San Jose",
      "state": "CA",
      "street": "Halsey Street"
    },
    {
      "name": "Bettie Woods",
      "rating": 1.1,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "bettiewoods@uniworld.com",
      "phone": "+1 (953) 600-2094",
      "city": "Concord",
      "state": "CA",
      "street": "Grand Avenue"
    },
    {
      "name": "Galloway Mullen",
      "rating": 4.3,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "gallowaymullen@uniworld.com",
      "phone": "+1 (869) 526-3336",
      "city": "San Jose",
      "state": "CA",
      "street": "Poplar Street"
    },
    {
      "name": "Kenya Evans",
      "rating": 4.2,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "kenyaevans@uniworld.com",
      "phone": "+1 (931) 555-3795",
      "city": "San Jose",
      "state": "CA",
      "street": "Grimes Road"
    },
    {
      "name": "Bauer Patton",
      "rating": 2.1,
      "speciality": "Surgery",
      "gender": "male",
      "email": "bauerpatton@uniworld.com",
      "phone": "+1 (958) 406-3508",
      "city": "Concord",
      "state": "CA",
      "street": "Calyer Street"
    },
    {
      "name": "Estella Hanson",
      "rating": 4.1,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "estellahanson@uniworld.com",
      "phone": "+1 (840) 415-3610",
      "city": "San Jose",
      "state": "CA",
      "street": "Bennet Court"
    },
    {
      "name": "Foster Paul",
      "rating": 2,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "fosterpaul@uniworld.com",
      "phone": "+1 (946) 556-2051",
      "city": "Concord",
      "state": "CA",
      "street": "Balfour Place"
    },
    {
      "name": "Sondra Lowery",
      "rating": 2.9,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "sondralowery@uniworld.com",
      "phone": "+1 (953) 516-3018",
      "city": "Concord",
      "state": "CA",
      "street": "Cypress Avenue"
    },
    {
      "name": "Knox Cortez",
      "rating": 1.7,
      "speciality": "Surgery",
      "gender": "male",
      "email": "knoxcortez@uniworld.com",
      "phone": "+1 (874) 472-3464",
      "city": "Concord",
      "state": "CA",
      "street": "Denton Place"
    },
    {
      "name": "Trina Kline",
      "rating": 3.9,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "trinakline@uniworld.com",
      "phone": "+1 (996) 408-2815",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Applegate Court"
    },
    {
      "name": "Walter Dorsey",
      "rating": 2.6,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "walterdorsey@uniworld.com",
      "phone": "+1 (825) 583-2599",
      "city": "San Francisco",
      "state": "CA",
      "street": "Hegeman Avenue"
    },
    {
      "name": "Pitts Hess",
      "rating": 1.2,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "pittshess@uniworld.com",
      "phone": "+1 (836) 585-3503",
      "city": "San Jose",
      "state": "CA",
      "street": "Atlantic Avenue"
    },
    {
      "name": "Castro Lane",
      "rating": 3.8,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "castrolane@uniworld.com",
      "phone": "+1 (919) 487-3593",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Strickland Avenue"
    },
    {
      "name": "Kris Gay",
      "rating": 1.8,
      "speciality": "Surgery",
      "gender": "female",
      "email": "krisgay@uniworld.com",
      "phone": "+1 (835) 541-3402",
      "city": "Oakland",
      "state": "CA",
      "street": "Nautilus Avenue"
    },
    {
      "name": "Alyson Glass",
      "rating": 1.3,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "alysonglass@uniworld.com",
      "phone": "+1 (856) 406-2394",
      "city": "San Jose",
      "state": "CA",
      "street": "Nassau Street"
    },
    {
      "name": "Katherine Farmer",
      "rating": 1,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "katherinefarmer@uniworld.com",
      "phone": "+1 (909) 487-3440",
      "city": "Oakland",
      "state": "CA",
      "street": "Campus Place"
    },
    {
      "name": "Francine Cote",
      "rating": 3.8,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "francinecote@uniworld.com",
      "phone": "+1 (918) 432-2632",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Vanderveer Place"
    },
    {
      "name": "Marshall Hodges",
      "rating": 3.9,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "marshallhodges@uniworld.com",
      "phone": "+1 (898) 416-2453",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Utica Avenue"
    },
    {
      "name": "Salazar Schroeder",
      "rating": 1.4,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "salazarschroeder@uniworld.com",
      "phone": "+1 (867) 576-3176",
      "city": "Oakland",
      "state": "CA",
      "street": "Beard Street"
    },
    {
      "name": "Farrell Gillespie",
      "rating": 5,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "farrellgillespie@uniworld.com",
      "phone": "+1 (945) 586-2444",
      "city": "Oakland",
      "state": "CA",
      "street": "Beverley Road"
    },
    {
      "name": "Yesenia Puckett",
      "rating": 1.8,
      "speciality": "Surgery",
      "gender": "female",
      "email": "yeseniapuckett@uniworld.com",
      "phone": "+1 (995) 565-2063",
      "city": "San Francisco",
      "state": "CA",
      "street": "Hancock Street"
    },
    {
      "name": "Byers Guerra",
      "rating": 1.6,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "byersguerra@uniworld.com",
      "phone": "+1 (963) 591-2016",
      "city": "Concord",
      "state": "CA",
      "street": "Autumn Avenue"
    },
    {
      "name": "Julia Wooten",
      "rating": 5,
      "speciality": "Surgery",
      "gender": "female",
      "email": "juliawooten@uniworld.com",
      "phone": "+1 (909) 559-3385",
      "city": "Concord",
      "state": "CA",
      "street": "Madison Place"
    },
    {
      "name": "Rae Ball",
      "rating": 4.5,
      "speciality": "Surgery",
      "gender": "female",
      "email": "raeball@uniworld.com",
      "phone": "+1 (861) 563-3335",
      "city": "Concord",
      "state": "CA",
      "street": "Legion Street"
    },
    {
      "name": "Mccoy Goodwin",
      "rating": 3.7,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "mccoygoodwin@uniworld.com",
      "phone": "+1 (844) 521-3596",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Essex Street"
    },
    {
      "name": "Koch Huffman",
      "rating": 3.2,
      "speciality": "Surgery",
      "gender": "male",
      "email": "kochhuffman@uniworld.com",
      "phone": "+1 (981) 470-2585",
      "city": "San Jose",
      "state": "CA",
      "street": "Quay Street"
    },
    {
      "name": "Mandy Roy",
      "rating": 1.5,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "mandyroy@uniworld.com",
      "phone": "+1 (988) 468-2975",
      "city": "Concord",
      "state": "CA",
      "street": "Bergen Avenue"
    },
    {
      "name": "Angelica Watkins",
      "rating": 5,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "angelicawatkins@uniworld.com",
      "phone": "+1 (889) 590-3462",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Wyona Street"
    },
    {
      "name": "Cochran Murphy",
      "rating": 1.7,
      "speciality": "Surgery",
      "gender": "male",
      "email": "cochranmurphy@uniworld.com",
      "phone": "+1 (801) 550-3796",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Livonia Avenue"
    },
    {
      "name": "Alma Adams",
      "rating": 2.3,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "almaadams@uniworld.com",
      "phone": "+1 (886) 445-2691",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Withers Street"
    },
    {
      "name": "Joni Blevins",
      "rating": 1.6,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "joniblevins@uniworld.com",
      "phone": "+1 (876) 423-2515",
      "city": "San Francisco",
      "state": "CA",
      "street": "Carlton Avenue"
    },
    {
      "name": "Chen Salinas",
      "rating": 4.2,
      "speciality": "Surgery",
      "gender": "male",
      "email": "chensalinas@uniworld.com",
      "phone": "+1 (968) 477-2521",
      "city": "Concord",
      "state": "CA",
      "street": "Gain Court"
    },
    {
      "name": "Bethany Fernandez",
      "rating": 4.1,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "bethanyfernandez@uniworld.com",
      "phone": "+1 (974) 474-2128",
      "city": "Concord",
      "state": "CA",
      "street": "Elizabeth Place"
    },
    {
      "name": "Byrd Bryan",
      "rating": 4,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "byrdbryan@uniworld.com",
      "phone": "+1 (946) 540-2292",
      "city": "San Jose",
      "state": "CA",
      "street": "Bogart Street"
    },
    {
      "name": "Prince Galloway",
      "rating": 3.5,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "princegalloway@uniworld.com",
      "phone": "+1 (960) 437-2260",
      "city": "Oakland",
      "state": "CA",
      "street": "Grafton Street"
    },
    {
      "name": "Aurora Murray",
      "rating": 1.6,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "auroramurray@uniworld.com",
      "phone": "+1 (822) 555-2881",
      "city": "Concord",
      "state": "CA",
      "street": "Kimball Street"
    },
    {
      "name": "Miriam Alford",
      "rating": 4.5,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "miriamalford@uniworld.com",
      "phone": "+1 (899) 596-3488",
      "city": "Oakland",
      "state": "CA",
      "street": "Ainslie Street"
    },
    {
      "name": "Oliver Campos",
      "rating": 4.5,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "olivercampos@uniworld.com",
      "phone": "+1 (846) 585-3722",
      "city": "Oakland",
      "state": "CA",
      "street": "Classon Avenue"
    },
    {
      "name": "Bright Pacheco",
      "rating": 3.4,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "brightpacheco@uniworld.com",
      "phone": "+1 (939) 525-3003",
      "city": "San Jose",
      "state": "CA",
      "street": "Schenck Avenue"
    },
    {
      "name": "Geneva Lamb",
      "rating": 2.5,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "genevalamb@uniworld.com",
      "phone": "+1 (948) 578-2858",
      "city": "Concord",
      "state": "CA",
      "street": "Olive Street"
    },
    {
      "name": "Alvarado Knowles",
      "rating": 2.8,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "alvaradoknowles@uniworld.com",
      "phone": "+1 (805) 403-2765",
      "city": "San Jose",
      "state": "CA",
      "street": "Coffey Street"
    },
    {
      "name": "Mcdonald Fuller",
      "rating": 3.9,
      "speciality": "Surgery",
      "gender": "male",
      "email": "mcdonaldfuller@uniworld.com",
      "phone": "+1 (820) 449-2653",
      "city": "Concord",
      "state": "CA",
      "street": "Kenilworth Place"
    },
    {
      "name": "Mcconnell Bentley",
      "rating": 4.4,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "mcconnellbentley@uniworld.com",
      "phone": "+1 (842) 433-3479",
      "city": "San Jose",
      "state": "CA",
      "street": "Fillmore Avenue"
    },
    {
      "name": "Sweet Robinson",
      "rating": 3.1,
      "speciality": "Surgery",
      "gender": "male",
      "email": "sweetrobinson@uniworld.com",
      "phone": "+1 (933) 585-2980",
      "city": "Oakland",
      "state": "CA",
      "street": "Beayer Place"
    },
    {
      "name": "Rosanna Rasmussen",
      "rating": 3.6,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "rosannarasmussen@uniworld.com",
      "phone": "+1 (896) 402-3518",
      "city": "San Francisco",
      "state": "CA",
      "street": "Erasmus Street"
    },
    {
      "name": "Whitehead Hammond",
      "rating": 3.1,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "whiteheadhammond@uniworld.com",
      "phone": "+1 (918) 579-2716",
      "city": "San Francisco",
      "state": "CA",
      "street": "Grove Place"
    },
    {
      "name": "Lydia Wagner",
      "rating": 4.7,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "lydiawagner@uniworld.com",
      "phone": "+1 (914) 506-3359",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Dinsmore Place"
    },
    {
      "name": "Gabrielle Pace",
      "rating": 3.2,
      "speciality": "Surgery",
      "gender": "female",
      "email": "gabriellepace@uniworld.com",
      "phone": "+1 (815) 522-2090",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Wythe Place"
    },
    {
      "name": "George Hull",
      "rating": 2.7,
      "speciality": "Surgery",
      "gender": "male",
      "email": "georgehull@uniworld.com",
      "phone": "+1 (960) 400-3524",
      "city": "San Jose",
      "state": "CA",
      "street": "Dahl Court"
    },
    {
      "name": "Teresa Davenport",
      "rating": 2.2,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "teresadavenport@uniworld.com",
      "phone": "+1 (877) 473-2367",
      "city": "Concord",
      "state": "CA",
      "street": "Hubbard Street"
    },
    {
      "name": "Collins Holman",
      "rating": 2.6,
      "speciality": "Surgery",
      "gender": "male",
      "email": "collinsholman@uniworld.com",
      "phone": "+1 (857) 412-2254",
      "city": "San Jose",
      "state": "CA",
      "street": "Clarendon Road"
    },
    {
      "name": "Beatriz Armstrong",
      "rating": 1.5,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "beatrizarmstrong@uniworld.com",
      "phone": "+1 (981) 549-3109",
      "city": "Concord",
      "state": "CA",
      "street": "Oriental Boulevard"
    },
    {
      "name": "Lee Conway",
      "rating": 3.4,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "leeconway@uniworld.com",
      "phone": "+1 (920) 453-2405",
      "city": "San Jose",
      "state": "CA",
      "street": "Garnet Street"
    },
    {
      "name": "Fleming Phillips",
      "rating": 4,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "flemingphillips@uniworld.com",
      "phone": "+1 (887) 586-2487",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Rutledge Street"
    },
    {
      "name": "Wise Rhodes",
      "rating": 3.9,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "wiserhodes@uniworld.com",
      "phone": "+1 (808) 561-2905",
      "city": "Concord",
      "state": "CA",
      "street": "Porter Avenue"
    },
    {
      "name": "Savage Oneil",
      "rating": 3.6,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "savageoneil@uniworld.com",
      "phone": "+1 (944) 513-3268",
      "city": "San Francisco",
      "state": "CA",
      "street": "Onderdonk Avenue"
    },
    {
      "name": "Brittany Carlson",
      "rating": 3.1,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "brittanycarlson@uniworld.com",
      "phone": "+1 (966) 591-2320",
      "city": "Santa Clara",
      "state": "CA",
      "street": "King Street"
    },
    {
      "name": "Jenny Navarro",
      "rating": 5,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "jennynavarro@uniworld.com",
      "phone": "+1 (977) 590-3623",
      "city": "Oakland",
      "state": "CA",
      "street": "Rockaway Avenue"
    },
    {
      "name": "Becky Finley",
      "rating": 1.9,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "beckyfinley@uniworld.com",
      "phone": "+1 (823) 516-3740",
      "city": "San Jose",
      "state": "CA",
      "street": "Llama Court"
    },
    {
      "name": "Quinn Charles",
      "rating": 1,
      "speciality": "Surgery",
      "gender": "male",
      "email": "quinncharles@uniworld.com",
      "phone": "+1 (921) 528-2231",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Decatur Street"
    },
    {
      "name": "Bobbi Keller",
      "rating": 1,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "bobbikeller@uniworld.com",
      "phone": "+1 (824) 520-2983",
      "city": "Oakland",
      "state": "CA",
      "street": "Winthrop Street"
    },
    {
      "name": "Keller Kent",
      "rating": 3.2,
      "speciality": "Surgery",
      "gender": "male",
      "email": "kellerkent@uniworld.com",
      "phone": "+1 (896) 597-2827",
      "city": "San Jose",
      "state": "CA",
      "street": "Sapphire Street"
    },
    {
      "name": "Nichole Meadows",
      "rating": 3.3,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "nicholemeadows@uniworld.com",
      "phone": "+1 (891) 510-2620",
      "city": "Concord",
      "state": "CA",
      "street": "Just Court"
    },
    {
      "name": "Tammi Melendez",
      "rating": 4.4,
      "speciality": "Surgery",
      "gender": "female",
      "email": "tammimelendez@uniworld.com",
      "phone": "+1 (914) 598-2974",
      "city": "San Jose",
      "state": "CA",
      "street": "Maple Street"
    },
    {
      "name": "Jeanine Bradshaw",
      "rating": 1,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "jeaninebradshaw@uniworld.com",
      "phone": "+1 (856) 499-2084",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Raleigh Place"
    },
    {
      "name": "Norman Harrison",
      "rating": 3.3,
      "speciality": "Dentistry",
      "gender": "male",
      "email": "normanharrison@uniworld.com",
      "phone": "+1 (930) 427-3226",
      "city": "San Francisco",
      "state": "CA",
      "street": "Henderson Walk"
    },
    {
      "name": "Yates Spears",
      "rating": 2.5,
      "speciality": "Surgery",
      "gender": "male",
      "email": "yatesspears@uniworld.com",
      "phone": "+1 (982) 412-3163",
      "city": "San Jose",
      "state": "CA",
      "street": "Suydam Place"
    },
    {
      "name": "Ana Burton",
      "rating": 2.7,
      "speciality": "Psychiatry",
      "gender": "female",
      "email": "anaburton@uniworld.com",
      "phone": "+1 (860) 598-3993",
      "city": "Oakland",
      "state": "CA",
      "street": "Bushwick Place"
    },
    {
      "name": "Mayo Gross",
      "rating": 2.2,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "mayogross@uniworld.com",
      "phone": "+1 (891) 491-3449",
      "city": "Concord",
      "state": "CA",
      "street": "Bevy Court"
    },
    {
      "name": "Clark Rodgers",
      "rating": 4.8,
      "speciality": "Physical Therapy",
      "gender": "male",
      "email": "clarkrodgers@uniworld.com",
      "phone": "+1 (843) 546-2451",
      "city": "Oakland",
      "state": "CA",
      "street": "Village Road"
    },
    {
      "name": "Whitley Atkinson",
      "rating": 4,
      "speciality": "Surgery",
      "gender": "male",
      "email": "whitleyatkinson@uniworld.com",
      "phone": "+1 (911) 510-3327",
      "city": "San Francisco",
      "state": "CA",
      "street": "Bradford Street"
    },
    {
      "name": "Eileen Johns",
      "rating": 1.5,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "eileenjohns@uniworld.com",
      "phone": "+1 (803) 574-2272",
      "city": "Oakland",
      "state": "CA",
      "street": "Chestnut Avenue"
    },
    {
      "name": "Lucia Villarreal",
      "rating": 3.7,
      "speciality": "Surgery",
      "gender": "female",
      "email": "luciavillarreal@uniworld.com",
      "phone": "+1 (863) 528-2894",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Jackson Street"
    },
    {
      "name": "Gamble Cooke",
      "rating": 3,
      "speciality": "Surgery",
      "gender": "male",
      "email": "gamblecooke@uniworld.com",
      "phone": "+1 (983) 438-2872",
      "city": "Walnut Creek",
      "state": "CA",
      "street": "Putnam Avenue"
    },
    {
      "name": "Vaughan Hoffman",
      "rating": 3.6,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "vaughanhoffman@uniworld.com",
      "phone": "+1 (852) 422-2240",
      "city": "San Jose",
      "state": "CA",
      "street": "Prospect Place"
    },
    {
      "name": "Estrada Summers",
      "rating": 5,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "estradasummers@uniworld.com",
      "phone": "+1 (855) 582-2757",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Gem Street"
    },
    {
      "name": "Lenora Woodward",
      "rating": 4.6,
      "speciality": "Psychiatry",
      "gender": "female",
      "email": "lenorawoodward@uniworld.com",
      "phone": "+1 (890) 540-3253",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Holmes Lane"
    },
    {
      "name": "Earlene Franklin",
      "rating": 2.8,
      "speciality": "Dermatology",
      "gender": "female",
      "email": "earlenefranklin@uniworld.com",
      "phone": "+1 (924) 490-2693",
      "city": "Oakland",
      "state": "CA",
      "street": "Juliana Place"
    },
    {
      "name": "Adrian Hahn",
      "rating": 2,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "adrianhahn@uniworld.com",
      "phone": "+1 (840) 479-3473",
      "city": "Santa Clara",
      "state": "CA",
      "street": "Reed Street"
    },
    {
      "name": "Charlene Leach",
      "rating": 2.3,
      "speciality": "Dentistry",
      "gender": "female",
      "email": "charleneleach@uniworld.com",
      "phone": "+1 (943) 438-2219",
      "city": "San Jose",
      "state": "CA",
      "street": "Montauk Avenue"
    },
    {
      "name": "Cynthia Mcintosh",
      "rating": 1.2,
      "speciality": "Physical Therapy",
      "gender": "female",
      "email": "cynthiamcintosh@uniworld.com",
      "phone": "+1 (953) 430-2248",
      "city": "Oakland",
      "state": "CA",
      "street": "Seabring Street"
    },
    {
      "name": "Phillips Hendrix",
      "rating": 2.7,
      "speciality": "Psychiatry",
      "gender": "male",
      "email": "phillipshendrix@uniworld.com",
      "phone": "+1 (970) 566-3416",
      "city": "Oakland",
      "state": "CA",
      "street": "Clarkson Avenue"
    },
    {
      "name": "Porter Burks",
      "rating": 4.3,
      "speciality": "Dermatology",
      "gender": "male",
      "email": "porterburks@uniworld.com",
      "phone": "+1 (912) 539-3923",
      "city": "San Jose",
      "state": "CA",
      "street": "Lott Avenue"
    }
  ]

  export default Data